// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace RoadRunnerNew.iOS
{
	public partial class PaddingTextView : UITextField
	{
		public PaddingTextView (IntPtr handle) : base (handle)
		{
		}
	}
}
