#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("RoadRunner.Android.Resource", IsApplication=true)]

namespace RoadRunner.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::RoadRunner.Android.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::RoadRunner.Android.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::RoadRunner.Android.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::RoadRunner.Android.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::RoadRunner.Android.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::RoadRunner.Android.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::RoadRunner.Android.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::RoadRunner.Android.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::RoadRunner.Android.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::RoadRunner.Android.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::RoadRunner.Android.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::RoadRunner.Android.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::RoadRunner.Android.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::RoadRunner.Android.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::RoadRunner.Android.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::RoadRunner.Android.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::RoadRunner.Android.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::RoadRunner.Android.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::RoadRunner.Android.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::RoadRunner.Android.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::RoadRunner.Android.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::RoadRunner.Android.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::RoadRunner.Android.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::RoadRunner.Android.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::RoadRunner.Android.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::RoadRunner.Android.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::RoadRunner.Android.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::RoadRunner.Android.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::RoadRunner.Android.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::RoadRunner.Android.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::RoadRunner.Android.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::RoadRunner.Android.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::RoadRunner.Android.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::RoadRunner.Android.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::RoadRunner.Android.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::RoadRunner.Android.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::RoadRunner.Android.Resource.Styleable.ProgressWheel_ahTextSize;
			global::GalaSoft.MvvmLight.Resource.String.ApplicationName = global::RoadRunner.Android.Resource.String.ApplicationName;
			global::GalaSoft.MvvmLight.Resource.String.Hello = global::RoadRunner.Android.Resource.String.Hello;
			global::FacebookMonoDroid.Resource.String.library_name = global::RoadRunner.Android.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int back = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fromLeft = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int fromRight = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int toLeft = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int toRight = 2130968580;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01001a
			public const int ahBarColor = 2130771994;
			
			// aapt resource value: 0x7f010022
			public const int ahBarLength = 2130772002;
			
			// aapt resource value: 0x7f010021
			public const int ahBarWidth = 2130772001;
			
			// aapt resource value: 0x7f01001f
			public const int ahCircleColor = 2130771999;
			
			// aapt resource value: 0x7f01001e
			public const int ahDelayMillis = 2130771998;
			
			// aapt resource value: 0x7f010020
			public const int ahRadius = 2130772000;
			
			// aapt resource value: 0x7f01001b
			public const int ahRimColor = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int ahRimWidth = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int ahSpinSpeed = 2130771997;
			
			// aapt resource value: 0x7f010017
			public const int ahText = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int ahTextColor = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int ahTextSize = 2130771993;
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int buttonSize = 2130771985;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010016
			public const int circleCrop = 2130771990;
			
			// aapt resource value: 0x7f010012
			public const int colorScheme = 2130771986;
			
			// aapt resource value: 0x7f010015
			public const int imageAspectRatio = 2130771989;
			
			// aapt resource value: 0x7f010014
			public const int imageAspectRatioAdjust = 2130771988;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010013
			public const int scopeUris = 2130771987;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public const int common_action_bar_splitter = 2131034120;
			
			// aapt resource value: 0x7f05001a
			public const int common_google_signin_btn_text_dark = 2131034138;
			
			// aapt resource value: 0x7f050009
			public const int common_google_signin_btn_text_dark_default = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_signin_btn_text_dark_disabled = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_signin_btn_text_dark_focused = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_signin_btn_text_dark_pressed = 2131034122;
			
			// aapt resource value: 0x7f05001b
			public const int common_google_signin_btn_text_light = 2131034139;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_signin_btn_text_light_default = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_signin_btn_text_light_disabled = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int common_google_signin_btn_text_light_focused = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_signin_btn_text_light_pressed = 2131034126;
			
			// aapt resource value: 0x7f05001c
			public const int common_plus_signin_btn_text_dark = 2131034140;
			
			// aapt resource value: 0x7f050000
			public const int common_plus_signin_btn_text_dark_default = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_plus_signin_btn_text_dark_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_plus_signin_btn_text_dark_focused = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_plus_signin_btn_text_dark_pressed = 2131034113;
			
			// aapt resource value: 0x7f05001d
			public const int common_plus_signin_btn_text_light = 2131034141;
			
			// aapt resource value: 0x7f050004
			public const int common_plus_signin_btn_text_light_default = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int common_plus_signin_btn_text_light_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_plus_signin_btn_text_light_focused = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int common_plus_signin_btn_text_light_pressed = 2131034117;
			
			// aapt resource value: 0x7f050011
			public const int common_signin_btn_dark_text_default = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int common_signin_btn_dark_text_disabled = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int common_signin_btn_dark_text_focused = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int common_signin_btn_dark_text_pressed = 2131034130;
			
			// aapt resource value: 0x7f050019
			public const int common_signin_btn_default_background = 2131034137;
			
			// aapt resource value: 0x7f050015
			public const int common_signin_btn_light_text_default = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int common_signin_btn_light_text_disabled = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int common_signin_btn_light_text_focused = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int common_signin_btn_light_text_pressed = 2131034134;
			
			// aapt resource value: 0x7f05001e
			public const int common_signin_btn_text_dark = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int common_signin_btn_text_light = 2131034143;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg_login = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btnCancelTrip = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btnReadyForPickup = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int card_amer = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int card_diner = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int card_discover = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int card_master = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int card_visa = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_full_open_on_phone = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_dark = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_dark_disabled = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_dark_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_dark_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_icon_dark_pressed = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_icon_light = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_icon_light_disabled = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_icon_light_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_icon_light_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_icon_light_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_dark_disabled = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_dark_focused = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_dark_normal = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_text_dark_pressed = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_google_signin_btn_text_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_google_signin_btn_text_light_disabled = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_google_signin_btn_text_light_focused = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_google_signin_btn_text_light_normal = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_google_signin_btn_text_light_pressed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_ic_googleplayservices = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_icon_dark_focused = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_icon_dark_normal = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_icon_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_icon_light_disabled = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_icon_light_focused = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_icon_light_normal = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_icon_light_pressed = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_dark = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_dark_disabled = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_plus_signin_btn_text_dark_focused = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_plus_signin_btn_text_dark_normal = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int common_plus_signin_btn_text_dark_pressed = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int common_plus_signin_btn_text_light = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int common_plus_signin_btn_text_light_disabled = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int common_plus_signin_btn_text_light_focused = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int common_plus_signin_btn_text_light_normal = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int common_plus_signin_btn_text_light_pressed = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int common_signin_btn_icon_dark = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int common_signin_btn_icon_disabled_dark = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int common_signin_btn_icon_disabled_focus_light = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int common_signin_btn_icon_disabled_light = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int common_signin_btn_icon_focus_dark = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int common_signin_btn_icon_focus_light = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int common_signin_btn_icon_light = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int common_signin_btn_icon_normal_dark = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int common_signin_btn_icon_normal_light = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int common_signin_btn_icon_pressed_dark = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int common_signin_btn_icon_pressed_light = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int common_signin_btn_text_dark = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int common_signin_btn_text_disabled_dark = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int common_signin_btn_text_disabled_focus_dark = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int common_signin_btn_text_disabled_focus_light = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int common_signin_btn_text_disabled_light = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int common_signin_btn_text_focus_dark = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int common_signin_btn_text_focus_light = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int common_signin_btn_text_light = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int common_signin_btn_text_normal_dark = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int common_signin_btn_text_normal_light = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int common_signin_btn_text_pressed_dark = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int common_signin_btn_text_pressed_light = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int component_rbtn_selector = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int component_rbtn_textcolor_selector = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int ic_errorstatus = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int ic_plusone_medium_off_client = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int ic_plusone_small_off_client = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int ic_plusone_standard_off_client = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int ic_plusone_tall_off_client = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int ic_successstatus = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int Icon = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int icon_add = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int icon_avatar = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int icon_back = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int icon_calendar = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int icon_car = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int icon_card = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int icon_circle = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int icon_default_flight = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int icon_email = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int icon_facebook = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int icon_gift = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int icon_google = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int icon_home = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int icon_linkedin = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int icon_login = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int icon_loginwith = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int icon_mark = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int icon_menu = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int icon_password = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int icon_phone = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int icon_search = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int icon_signup = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int icon_user = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int icon_wheelchair = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int icon_zip = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int micon_clock = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int micon_payment = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int micon_setting = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int micon_support = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int micon_terms = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int micon_user = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int my_button = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int roundedbg = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int roundedbgdark = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int s_vehicle_black = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int s_vehicle_bus = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int s_vehicle_limo = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int s_vehicle_private = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int s_vehicle_shared = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int s_vehicle_suv = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int s_vehicle_wheel = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int vehicle_black = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int vehicle_bus = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int vehicle_limo = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int vehicle_private = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int vehicle_suv = 2130837632;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000b
			public const int adjust_height = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int adjust_width = 2131230732;
			
			// aapt resource value: 0x7f080008
			public const int auto = 2131230728;
			
			// aapt resource value: 0x7f080095
			public const int avatar = 2131230869;
			
			// aapt resource value: 0x7f080069
			public const int btnAddCard = 2131230825;
			
			// aapt resource value: 0x7f080057
			public const int btnAddPayment = 2131230807;
			
			// aapt resource value: 0x7f08005a
			public const int btnBookARide = 2131230810;
			
			// aapt resource value: 0x7f080077
			public const int btnCancel = 2131230839;
			
			// aapt resource value: 0x7f0800e7
			public const int btnConfirmRegistration = 2131230951;
			
			// aapt resource value: 0x7f080076
			public const int btnEdit = 2131230838;
			
			// aapt resource value: 0x7f08008b
			public const int btnFacebook = 2131230859;
			
			// aapt resource value: 0x7f080089
			public const int btnForgot = 2131230857;
			
			// aapt resource value: 0x7f08008d
			public const int btnGoogle = 2131230861;
			
			// aapt resource value: 0x7f08008c
			public const int btnLinkedin = 2131230860;
			
			// aapt resource value: 0x7f080088
			public const int btnLogin = 2131230856;
			
			// aapt resource value: 0x7f080053
			public const int btnReset = 2131230803;
			
			// aapt resource value: 0x7f080039
			public const int btnScanCard = 2131230777;
			
			// aapt resource value: 0x7f080048
			public const int btnSetDateTime = 2131230792;
			
			// aapt resource value: 0x7f08008a
			public const int btnSignUp = 2131230858;
			
			// aapt resource value: 0x7f080034
			public const int btnSubmit = 2131230772;
			
			// aapt resource value: 0x7f0800e6
			public const int btnTerms = 2131230950;
			
			// aapt resource value: 0x7f080058
			public const int btnVerifyPromo = 2131230808;
			
			// aapt resource value: 0x7f0800e9
			public const int btn_Done = 2131230953;
			
			// aapt resource value: 0x7f080060
			public const int btn_GoToLocation = 2131230816;
			
			// aapt resource value: 0x7f0800de
			public const int btn_GoToRideConfirmation = 2131230942;
			
			// aapt resource value: 0x7f080081
			public const int btn_GoToRidePayment = 2131230849;
			
			// aapt resource value: 0x7f0800ae
			public const int btn_GoToThankyou = 2131230894;
			
			// aapt resource value: 0x7f0800e8
			public const int btn_Return = 2131230952;
			
			// aapt resource value: 0x7f08000e
			public const int btn_back = 2131230734;
			
			// aapt resource value: 0x7f080059
			public const int button3 = 2131230809;
			
			// aapt resource value: 0x7f08001b
			public const int cardImage = 2131230747;
			
			// aapt resource value: 0x7f08004a
			public const int contentLinear = 2131230794;
			
			// aapt resource value: 0x7f08005f
			public const int creditCardList = 2131230815;
			
			// aapt resource value: 0x7f080009
			public const int dark = 2131230729;
			
			// aapt resource value: 0x7f08006c
			public const int date = 2131230828;
			
			// aapt resource value: 0x7f08003e
			public const int datePicker = 2131230782;
			
			// aapt resource value: 0x7f08008e
			public const int drawerLayout = 2131230862;
			
			// aapt resource value: 0x7f080093
			public const int drawerPane = 2131230867;
			
			// aapt resource value: 0x7f08007e
			public const int editText3 = 2131230846;
			
			// aapt resource value: 0x7f080023
			public const int edtCCV = 2131230755;
			
			// aapt resource value: 0x7f08001d
			public const int edtCardData = 2131230749;
			
			// aapt resource value: 0x7f080032
			public const int edtCardDate = 2131230770;
			
			// aapt resource value: 0x7f08002d
			public const int edtCardName = 2131230765;
			
			// aapt resource value: 0x7f0800e1
			public const int edtEmailAddress = 2131230945;
			
			// aapt resource value: 0x7f0800df
			public const int edtFirstName = 2131230943;
			
			// aapt resource value: 0x7f0800e0
			public const int edtLastName = 2131230944;
			
			// aapt resource value: 0x7f0800e4
			public const int edtMobileNumber = 2131230948;
			
			// aapt resource value: 0x7f0800e2
			public const int edtPassword = 2131230946;
			
			// aapt resource value: 0x7f0800e3
			public const int edtRepeatPassword = 2131230947;
			
			// aapt resource value: 0x7f080028
			public const int edtZIP = 2131230760;
			
			// aapt resource value: 0x7f08003c
			public const int frameLayout1 = 2131230780;
			
			// aapt resource value: 0x7f08003d
			public const int frameLayout2 = 2131230781;
			
			// aapt resource value: 0x7f080042
			public const int frameLayout3 = 2131230786;
			
			// aapt resource value: 0x7f0800c7
			public const int frameLayout4 = 2131230919;
			
			// aapt resource value: 0x7f080000
			public const int hybrid = 2131230720;
			
			// aapt resource value: 0x7f080074
			public const int icon = 2131230836;
			
			// aapt resource value: 0x7f08009d
			public const int iconDropoff = 2131230877;
			
			// aapt resource value: 0x7f08009a
			public const int iconPickup = 2131230874;
			
			// aapt resource value: 0x7f0800a0
			public const int iconVehicle = 2131230880;
			
			// aapt resource value: 0x7f080005
			public const int icon_only = 2131230725;
			
			// aapt resource value: 0x7f08006a
			public const int image = 2131230826;
			
			// aapt resource value: 0x7f080010
			public const int imageView1 = 2131230736;
			
			// aapt resource value: 0x7f080021
			public const int imageView2 = 2131230753;
			
			// aapt resource value: 0x7f080026
			public const int imageView3 = 2131230758;
			
			// aapt resource value: 0x7f08002b
			public const int imageView4 = 2131230763;
			
			// aapt resource value: 0x7f080030
			public const int imageView5 = 2131230768;
			
			// aapt resource value: 0x7f0800d8
			public const int imgPayment = 2131230936;
			
			// aapt resource value: 0x7f08009f
			public const int lblDropOffAddress = 2131230879;
			
			// aapt resource value: 0x7f08009e
			public const int lblDropoffDate = 2131230878;
			
			// aapt resource value: 0x7f0800aa
			public const int lblExtraBags = 2131230890;
			
			// aapt resource value: 0x7f0800a4
			public const int lblGasSurcharges = 2131230884;
			
			// aapt resource value: 0x7f0800a6
			public const int lblGratuity = 2131230886;
			
			// aapt resource value: 0x7f0800a8
			public const int lblMeetAndGreetFee = 2131230888;
			
			// aapt resource value: 0x7f0800dc
			public const int lblMeetandGreetFee = 2131230940;
			
			// aapt resource value: 0x7f08009c
			public const int lblPickUpAddress = 2131230876;
			
			// aapt resource value: 0x7f08009b
			public const int lblPickupDate = 2131230875;
			
			// aapt resource value: 0x7f0800a3
			public const int lblRideFee = 2131230883;
			
			// aapt resource value: 0x7f0800a1
			public const int lblRideType1 = 2131230881;
			
			// aapt resource value: 0x7f0800a2
			public const int lblRideType2 = 2131230882;
			
			// aapt resource value: 0x7f0800ac
			public const int lblTotal = 2131230892;
			
			// aapt resource value: 0x7f08000a
			public const int light = 2131230730;
			
			// aapt resource value: 0x7f080011
			public const int linearLayout1 = 2131230737;
			
			// aapt resource value: 0x7f080044
			public const int linearLayout10 = 2131230788;
			
			// aapt resource value: 0x7f080013
			public const int linearLayout11 = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int linearLayout12 = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int linearLayout13 = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int linearLayout14 = 2131230742;
			
			// aapt resource value: 0x7f08003b
			public const int linearLayout15 = 2131230779;
			
			// aapt resource value: 0x7f080017
			public const int linearLayout16 = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int linearLayout17 = 2131230744;
			
			// aapt resource value: 0x7f08003a
			public const int linearLayout18 = 2131230778;
			
			// aapt resource value: 0x7f080019
			public const int linearLayout19 = 2131230745;
			
			// aapt resource value: 0x7f080049
			public const int linearLayout2 = 2131230793;
			
			// aapt resource value: 0x7f080045
			public const int linearLayout20 = 2131230789;
			
			// aapt resource value: 0x7f080029
			public const int linearLayout21 = 2131230761;
			
			// aapt resource value: 0x7f08002e
			public const int linearLayout22 = 2131230766;
			
			// aapt resource value: 0x7f080033
			public const int linearLayout23 = 2131230771;
			
			// aapt resource value: 0x7f080035
			public const int linearLayout24 = 2131230773;
			
			// aapt resource value: 0x7f080038
			public const int linearLayout25 = 2131230776;
			
			// aapt resource value: 0x7f08001e
			public const int linearLayout26 = 2131230750;
			
			// aapt resource value: 0x7f08001f
			public const int linearLayout27 = 2131230751;
			
			// aapt resource value: 0x7f080024
			public const int linearLayout28 = 2131230756;
			
			// aapt resource value: 0x7f08001a
			public const int linearLayout29 = 2131230746;
			
			// aapt resource value: 0x7f080012
			public const int linearLayout3 = 2131230738;
			
			// aapt resource value: 0x7f08001c
			public const int linearLayout30 = 2131230748;
			
			// aapt resource value: 0x7f080020
			public const int linearLayout31 = 2131230752;
			
			// aapt resource value: 0x7f080022
			public const int linearLayout32 = 2131230754;
			
			// aapt resource value: 0x7f080027
			public const int linearLayout33 = 2131230759;
			
			// aapt resource value: 0x7f080025
			public const int linearLayout34 = 2131230757;
			
			// aapt resource value: 0x7f08002a
			public const int linearLayout35 = 2131230762;
			
			// aapt resource value: 0x7f08002c
			public const int linearLayout36 = 2131230764;
			
			// aapt resource value: 0x7f08002f
			public const int linearLayout37 = 2131230767;
			
			// aapt resource value: 0x7f080031
			public const int linearLayout38 = 2131230769;
			
			// aapt resource value: 0x7f080036
			public const int linearLayout39 = 2131230774;
			
			// aapt resource value: 0x7f080047
			public const int linearLayout4 = 2131230791;
			
			// aapt resource value: 0x7f080037
			public const int linearLayout40 = 2131230775;
			
			// aapt resource value: 0x7f0800d4
			public const int linearLayout41 = 2131230932;
			
			// aapt resource value: 0x7f0800ba
			public const int linearLayout42 = 2131230906;
			
			// aapt resource value: 0x7f0800bc
			public const int linearLayout43 = 2131230908;
			
			// aapt resource value: 0x7f0800be
			public const int linearLayout44 = 2131230910;
			
			// aapt resource value: 0x7f0800c0
			public const int linearLayout45 = 2131230912;
			
			// aapt resource value: 0x7f0800c2
			public const int linearLayout46 = 2131230914;
			
			// aapt resource value: 0x7f0800c4
			public const int linearLayout47 = 2131230916;
			
			// aapt resource value: 0x7f0800c6
			public const int linearLayout48 = 2131230918;
			
			// aapt resource value: 0x7f0800d5
			public const int linearLayout49 = 2131230933;
			
			// aapt resource value: 0x7f08004d
			public const int linearLayout5 = 2131230797;
			
			// aapt resource value: 0x7f08006d
			public const int linearLayout50 = 2131230829;
			
			// aapt resource value: 0x7f0800d7
			public const int linearLayout51 = 2131230935;
			
			// aapt resource value: 0x7f0800c8
			public const int linearLayout52 = 2131230920;
			
			// aapt resource value: 0x7f0800c9
			public const int linearLayout53 = 2131230921;
			
			// aapt resource value: 0x7f0800ca
			public const int linearLayout54 = 2131230922;
			
			// aapt resource value: 0x7f0800cb
			public const int linearLayout55 = 2131230923;
			
			// aapt resource value: 0x7f08003f
			public const int linearLayout6 = 2131230783;
			
			// aapt resource value: 0x7f080050
			public const int linearLayout7 = 2131230800;
			
			// aapt resource value: 0x7f080040
			public const int linearLayout8 = 2131230784;
			
			// aapt resource value: 0x7f080041
			public const int linearLayout9 = 2131230785;
			
			// aapt resource value: 0x7f08007a
			public const int loadingImage = 2131230842;
			
			// aapt resource value: 0x7f080078
			public const int loadingProgressBar = 2131230840;
			
			// aapt resource value: 0x7f08007b
			public const int loadingProgressWheel = 2131230843;
			
			// aapt resource value: 0x7f080099
			public const int location_list_view = 2131230873;
			
			// aapt resource value: 0x7f080087
			public const int login_password = 2131230855;
			
			// aapt resource value: 0x7f080085
			public const int login_username = 2131230853;
			
			// aapt resource value: 0x7f08008f
			public const int mainContent = 2131230863;
			
			// aapt resource value: 0x7f080092
			public const int mainFragmentContent = 2131230866;
			
			// aapt resource value: 0x7f080090
			public const int menuIconImgView = 2131230864;
			
			// aapt resource value: 0x7f080097
			public const int menuList = 2131230871;
			
			// aapt resource value: 0x7f080096
			public const int menu_userName = 2131230870;
			
			// aapt resource value: 0x7f08005e
			public const int myTripList = 2131230814;
			
			// aapt resource value: 0x7f080001
			public const int none = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int normal = 2131230722;
			
			// aapt resource value: 0x7f08006b
			public const int number = 2131230827;
			
			// aapt resource value: 0x7f080094
			public const int profileBox = 2131230868;
			
			// aapt resource value: 0x7f0800d3
			public const int radioAndroid1 = 2131230931;
			
			// aapt resource value: 0x7f0800d2
			public const int radioAndroid2 = 2131230930;
			
			// aapt resource value: 0x7f0800d1
			public const int radioAndroid3 = 2131230929;
			
			// aapt resource value: 0x7f0800d0
			public const int radioAndroid4 = 2131230928;
			
			// aapt resource value: 0x7f0800cf
			public const int radioAndroid5 = 2131230927;
			
			// aapt resource value: 0x7f0800ce
			public const int radioAndroid6 = 2131230926;
			
			// aapt resource value: 0x7f0800cd
			public const int radioAndroid7 = 2131230925;
			
			// aapt resource value: 0x7f0800b7
			public const int rb1 = 2131230903;
			
			// aapt resource value: 0x7f0800b8
			public const int rb2 = 2131230904;
			
			// aapt resource value: 0x7f0800b9
			public const int rb3 = 2131230905;
			
			// aapt resource value: 0x7f080052
			public const int relativeLayout1 = 2131230802;
			
			// aapt resource value: 0x7f0800b6
			public const int rgUpto = 2131230902;
			
			// aapt resource value: 0x7f0800cc
			public const int rgVehicle = 2131230924;
			
			// aapt resource value: 0x7f080003
			public const int satellite = 2131230723;
			
			// aapt resource value: 0x7f080098
			public const int searchText = 2131230872;
			
			// aapt resource value: 0x7f08005b
			public const int selectTripType = 2131230811;
			
			// aapt resource value: 0x7f0800dd
			public const int spExtraBags = 2131230941;
			
			// aapt resource value: 0x7f0800da
			public const int spGratuity = 2131230938;
			
			// aapt resource value: 0x7f0800b5
			public const int spHours = 2131230901;
			
			// aapt resource value: 0x7f0800b3
			public const int spPassengers = 2131230899;
			
			// aapt resource value: 0x7f0800d9
			public const int spPayment = 2131230937;
			
			// aapt resource value: 0x7f080055
			public const int spSelectPayment = 2131230805;
			
			// aapt resource value: 0x7f08004b
			public const int space1 = 2131230795;
			
			// aapt resource value: 0x7f0800a5
			public const int space2 = 2131230885;
			
			// aapt resource value: 0x7f0800a7
			public const int space3 = 2131230887;
			
			// aapt resource value: 0x7f0800a9
			public const int space4 = 2131230889;
			
			// aapt resource value: 0x7f0800ab
			public const int space5 = 2131230891;
			
			// aapt resource value: 0x7f0800ad
			public const int space6 = 2131230893;
			
			// aapt resource value: 0x7f08007d
			public const int spinner1 = 2131230845;
			
			// aapt resource value: 0x7f08007f
			public const int spinner2 = 2131230847;
			
			// aapt resource value: 0x7f080082
			public const int spinnerAirline = 2131230850;
			
			// aapt resource value: 0x7f080084
			public const int spinnerFlightType = 2131230852;
			
			// aapt resource value: 0x7f080006
			public const int standard = 2131230726;
			
			// aapt resource value: 0x7f0800e5
			public const int switchAgree = 2131230949;
			
			// aapt resource value: 0x7f0800db
			public const int switchMeetGreet = 2131230939;
			
			// aapt resource value: 0x7f0800b0
			public const int switchPorH = 2131230896;
			
			// aapt resource value: 0x7f080004
			public const int terrain = 2131230724;
			
			// aapt resource value: 0x7f080043
			public const int textView1 = 2131230787;
			
			// aapt resource value: 0x7f0800b2
			public const int textView11 = 2131230898;
			
			// aapt resource value: 0x7f0800b4
			public const int textView12 = 2131230900;
			
			// aapt resource value: 0x7f0800bb
			public const int textView13 = 2131230907;
			
			// aapt resource value: 0x7f0800bd
			public const int textView14 = 2131230909;
			
			// aapt resource value: 0x7f0800bf
			public const int textView15 = 2131230911;
			
			// aapt resource value: 0x7f0800c1
			public const int textView16 = 2131230913;
			
			// aapt resource value: 0x7f0800c3
			public const int textView17 = 2131230915;
			
			// aapt resource value: 0x7f0800c5
			public const int textView18 = 2131230917;
			
			// aapt resource value: 0x7f08004c
			public const int textView2 = 2131230796;
			
			// aapt resource value: 0x7f08004e
			public const int textView3 = 2131230798;
			
			// aapt resource value: 0x7f08004f
			public const int textView4 = 2131230799;
			
			// aapt resource value: 0x7f080062
			public const int textView5 = 2131230818;
			
			// aapt resource value: 0x7f080063
			public const int textView6 = 2131230819;
			
			// aapt resource value: 0x7f0800af
			public const int textView7 = 2131230895;
			
			// aapt resource value: 0x7f0800b1
			public const int textView8 = 2131230897;
			
			// aapt resource value: 0x7f080079
			public const int textViewStatus = 2131230841;
			
			// aapt resource value: 0x7f080046
			public const int timePicker = 2131230790;
			
			// aapt resource value: 0x7f080075
			public const int title = 2131230837;
			
			// aapt resource value: 0x7f08000d
			public const int titleBarLinearLayout = 2131230733;
			
			// aapt resource value: 0x7f080091
			public const int txtActionBarText = 2131230865;
			
			// aapt resource value: 0x7f080068
			public const int txtBody = 2131230824;
			
			// aapt resource value: 0x7f0800d6
			public const int txtComment = 2131230934;
			
			// aapt resource value: 0x7f080072
			public const int txtDropoffLocation = 2131230834;
			
			// aapt resource value: 0x7f080071
			public const int txtDropoffTime = 2131230833;
			
			// aapt resource value: 0x7f080051
			public const int txtEmail = 2131230801;
			
			// aapt resource value: 0x7f080083
			public const int txtFlightNumber = 2131230851;
			
			// aapt resource value: 0x7f080080
			public const int txtFlightTime = 2131230848;
			
			// aapt resource value: 0x7f080067
			public const int txtHeader = 2131230823;
			
			// aapt resource value: 0x7f080070
			public const int txtPickupLocation = 2131230832;
			
			// aapt resource value: 0x7f08006f
			public const int txtPickupTime = 2131230831;
			
			// aapt resource value: 0x7f080056
			public const int txtPromoCode = 2131230806;
			
			// aapt resource value: 0x7f08007c
			public const int txtRequestPickupDate = 2131230844;
			
			// aapt resource value: 0x7f080054
			public const int txtSearchLocation = 2131230804;
			
			// aapt resource value: 0x7f080061
			public const int txtSupportEmail = 2131230817;
			
			// aapt resource value: 0x7f080066
			public const int txtSupportFax = 2131230822;
			
			// aapt resource value: 0x7f080065
			public const int txtSupportFree = 2131230821;
			
			// aapt resource value: 0x7f080064
			public const int txtSupportPhone = 2131230820;
			
			// aapt resource value: 0x7f080073
			public const int txtTripDate = 2131230835;
			
			// aapt resource value: 0x7f08006e
			public const int txtTripID = 2131230830;
			
			// aapt resource value: 0x7f08005d
			public const int typeCompleted = 2131230813;
			
			// aapt resource value: 0x7f08005c
			public const int typeUpcoming = 2131230812;
			
			// aapt resource value: 0x7f08000f
			public const int v_book_ride = 2131230735;
			
			// aapt resource value: 0x7f080086
			public const int view1 = 2131230854;
			
			// aapt resource value: 0x7f080007
			public const int wide = 2131230727;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddPayment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DateTimePicker = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ForgotPassword = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_home = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_myTrips = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int fragment_paymentInfo = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int fragment_rideInformation = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int fragment_support = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int fragment_terms = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int item_addCard = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int item_card = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int item_completedTrip = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int item_location = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int item_menu = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int item_spinner = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int item_upcomingTrip = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int loading = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int loadingimage = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int loadingprogress = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int LocationDropoff = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int LocationPickup = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int LocationZip = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Login = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Main = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int PickupLocation = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int RideConfirmation = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int RideInformatioin = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int RidePayment = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int SignUp = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int Terms = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int ThankYou = 2130903070;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060027
			public const int ApplicationName = 2131099687;
			
			// aapt resource value: 0x7f060026
			public const int Hello = 2131099686;
			
			// aapt resource value: 0x7f060029
			public const int app_name = 2131099689;
			
			// aapt resource value: 0x7f060020
			public const int auth_client_needs_enabling_title = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int auth_client_needs_installation_title = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int auth_client_needs_update_title = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int auth_client_play_services_err_notification_msg = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int auth_client_requested_by_msg = 2131099684;
			
			// aapt resource value: 0x7f06001f
			public const int auth_client_using_bad_version_title = 2131099679;
			
			// aapt resource value: 0x7f06001d
			public const int auth_google_play_services_client_facebook_display_name = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int auth_google_play_services_client_google_display_name = 2131099676;
			
			// aapt resource value: 0x7f06002c
			public const int call_roadrunner = 2131099692;
			
			// aapt resource value: 0x7f060015
			public const int common_google_play_services_api_unavailable_text = 2131099669;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_enable_button = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_enable_text = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_enable_title = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_install_button = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_install_text_phone = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_install_text_tablet = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_install_title = 2131099649;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_invalid_account_text = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_invalid_account_title = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_network_error_text = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_network_error_title = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_notification_ticker = 2131099648;
			
			// aapt resource value: 0x7f060019
			public const int common_google_play_services_restricted_profile_text = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int common_google_play_services_restricted_profile_title = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int common_google_play_services_sign_in_failed_text = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int common_google_play_services_sign_in_failed_title = 2131099670;
			
			// aapt resource value: 0x7f06001e
			public const int common_google_play_services_unknown_issue = 2131099678;
			
			// aapt resource value: 0x7f060012
			public const int common_google_play_services_unsupported_text = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int common_google_play_services_unsupported_title = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int common_google_play_services_update_button = 2131099667;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_update_text = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_update_title = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_updating_text = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_updating_title = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_wear_update_text = 2131099658;
			
			// aapt resource value: 0x7f060014
			public const int common_open_on_phone = 2131099668;
			
			// aapt resource value: 0x7f06001a
			public const int common_signin_button_text = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int common_signin_button_text_long = 2131099675;
			
			// aapt resource value: 0x7f06002a
			public const int email_hint = 2131099690;
			
			// aapt resource value: 0x7f060028
			public const int hello = 2131099688;
			
			// aapt resource value: 0x7f060030
			public const int lbl_termsofservice = 2131099696;
			
			// aapt resource value: 0x7f060025
			public const int library_name = 2131099685;
			
			// aapt resource value: 0x7f060033
			public const int m_book_ride = 2131099699;
			
			// aapt resource value: 0x7f060032
			public const int m_home = 2131099698;
			
			// aapt resource value: 0x7f060038
			public const int m_logout = 2131099704;
			
			// aapt resource value: 0x7f060035
			public const int m_my_trip = 2131099701;
			
			// aapt resource value: 0x7f060034
			public const int m_payment = 2131099700;
			
			// aapt resource value: 0x7f060036
			public const int m_support = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int m_terms = 2131099703;
			
			// aapt resource value: 0x7f060031
			public const int m_user = 2131099697;
			
			// aapt resource value: 0x7f06002b
			public const int password_hint = 2131099691;
			
			// aapt resource value: 0x7f06003f
			public const int spinner_passengers = 2131099711;
			
			// aapt resource value: 0x7f06002d
			public const int support_email = 2131099693;
			
			// aapt resource value: 0x7f06002f
			public const int support_free = 2131099695;
			
			// aapt resource value: 0x7f06002e
			public const int support_phone = 2131099694;
			
			// aapt resource value: 0x7f06003a
			public const int v_book_ride = 2131099706;
			
			// aapt resource value: 0x7f060039
			public const int v_home = 2131099705;
			
			// aapt resource value: 0x7f06003c
			public const int v_my_trip = 2131099708;
			
			// aapt resource value: 0x7f06003b
			public const int v_payment = 2131099707;
			
			// aapt resource value: 0x7f06003d
			public const int v_support = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int v_terms = 2131099710;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] ProgressWheel = new int[]
			{
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			public static int[] SignInButton = new int[]
			{
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
